// <auto-generated />
namespace NBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newdiscussion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdiscussion));
        
        string IMigrationMetadata.Id
        {
            get { return "201907101525281_new-discussion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
