// <auto-generated />
namespace NBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AutoGenerate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoGenerate));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091535283_Auto-Generate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
